export const SIGNIN_REQUEST = '@auth/SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = '@auth/SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = '@auth/SIGNIN_FAILURE';
export const SIGNIN_RESET = '@auth/SIGNIN_RESET';

export const SIGNUP_REQUEST = '@auth/SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = '@auth/SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = '@auth/SIGNUP_FAILURE';
export const SIGNUP_RESET = '@auth/SIGNUP_RESET';

export const UPDATE_PROFILE_REQUEST = '@user/UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = '@user/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = '@user/UPDATE_PROFILE_FAILURE';